repo_name: zkan/ruby-on-rails-workshop
repo_url: https://github.com/zkan/ruby-on-rails-workshop/
site_name: Ruby on Rails Workshop
site_url: https://zkan.github.io/ruby-on-rails-workshop/

theme:
  name: material
  features:
    - content.code.copy
  palette:
    scheme: default
    primary: red
    accent: red

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - git-authors:
      show_email_address: false
  - git-revision-date-localized:
      enable_creation_date: false
  - search

nav:
  - Home: index.md
  - Setting up Your Development Environment: setting-up-your-development-environment.md 
  - Ruby Basics (+ Minitest): ruby-basics.md
  - Setting up a Ruby on Rails Project: setting-up-a-ruby-on-rails-project.md
  - Models, Views, and Controllers (+ Minitest): models-views-and-controllers.md
  - Forms: forms.md
  - Authentication (Default): authentication.md
  - Hotwire Basics: hotwire.md
  - Solid Cable, Solid Cache and Solid Queue: solid-cable-solid-cache-and-solid-queue.md
  - Deployment: deployment.md
  