repo_name: zkan/ruby-on-rails-workshop
repo_url: https://github.com/zkan/ruby-on-rails-workshop/
site_name: Ruby on Rails Workshop
site_url: https://zkan.github.io/ruby-on-rails-workshop/

theme:
  name: material
  features:
    - content.code.copy
  palette:
    scheme: default
    primary: red
    accent: red

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - git-authors:
      show_email_address: false
  - git-revision-date-localized:
      enable_creation_date: false
  - search

nav:
  - Home: index.md
